defaults:
  - base
  - _self_

num_seeds: 2
num_bootstrap: 5000
lora_path: /home/stefan/Documents/lora-composition/outputs/jerry_peanut_r32_d0/epoch_200
lora_name: jerry_peanut_r32_d0
character: jerry
