# @package _global_

defaults:
  - /base
  - _self_

composition:
  method: sum
  sources:
    - path: ./outputs/jerry_dop_lora_r32_p3/epoch_200
      weight: 0.5
    - path: ./outputs/george_dop_lora_r32_p3/epoch_200
      weight: 0.5
    - path: ./outputs/elaine_dop_lora_r32_p3/epoch_200
      weight: 0.5
    - path: ./outputs/kramer_dop_lora_r32_p3/epoch_200
      weight: 0.5

output_dir: ./outputs/compositions/sum
